services:
  postgres-db:
    image: postgres:15-alpine
    container_name: hospeda_db
    environment:
      POSTGRES_DB: hospedasync_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospeda-net

  redis-lock:
    image: redis:7-alpine
    container_name: hospeda_redis_lock
    ports:
      - "6379:6379"
    networks:
      - hospeda-net

  api-gateway:
    build: ./api-gateway
    container_name: hospeda_gateway
    ports:
      - "8000:8000"
    environment:
      - WORKER_SERVICE_URL=http://worker-node:8001
      - DATABASE_URL=postgresql+psycopg2://postgres:postgrespassword@postgres-db:5432/hospedasync_db
      - REDIS_URL=redis://redis-lock:6379/0
    depends_on:
      - postgres-db
      - redis-lock
    networks:
      - hospeda-net

  worker-node:
    build: ./workers
    container_name: hospeda_worker
    ports:
      - "8001:8001"
    environment:
      - GATEWAY_URL=http://api-gateway:8000
      - WORKER_ID=worker-01
      - PORT=8001
    depends_on:
      - api-gateway
    networks:
      - hospeda-net

networks:
  hospeda-net:
    driver: bridge

volumes:
  postgres_data: